source 'https://rubygems.org'

gem 'sinatra', '~> 4.1'
gem 'sinatra-cross_origin', '~> 0.4'
gem 'puma', '~> 7.2'
gem 'rackup'
gem 'jwt', '~> 3.2'
gem 'toml-rb', '~> 3.0'
gem 'dotenv', '~> 3.1'
gem 'json'
gem 'uri'
gem 'net-http'
